using System;
using System.Collections.Generic;

namespace LyricsPlayer;

public record LyricLine(double Time, string Text);

public record Song(
    string Title,
    string Subtitle,
    string AudioFile,
    IReadOnlyList<LyricLine> Lines,
    IReadOnlyDictionary<string, string> AvatarNames,
    IReadOnlyList<string> AllWords,
    IReadOnlyDictionary<string, string> CharTriggers,
    IReadOnlyDictionary<string, IReadOnlyList<string>>? AvatarKeywords = null,
    IReadOnlyDictionary<string, IReadOnlyList<string>>? AvatarExclude = null);

public static class LyricsData
{
    public static readonly Song[] Songs =
    {
        new(
            "最瞎結婚理由",
            "鋒兄 × 小塗 × 牙妹 × 魚妹｜今彩五三九牽紅線",
            "song1.mp3",
            new[]
            {
                new LyricLine(20.60, "鋒兄啊你說真的還假的"),
                new LyricLine(26.38, "小塗聽了都快笑翻了"),
                new LyricLine(32.30, "鋒兄說要結婚"),
                new LyricLine(35.10, "理由只有一個"),
                new LyricLine(38.23, "今彩五三九開獎那天"),
                new LyricLine(41.39, "頭獎號碼是牙妹給的"),
                new LyricLine(43.81, "看著獎金直直落"),
                new LyricLine(47.13, "心也跟著被收編"),
                new LyricLine(49.86, "他說這是命中注定"),
                new LyricLine(52.76, "不娶怎麼對得起這一連串的玄"),
                new LyricLine(58.76, "史上最瞎結婚理由"),
                new LyricLine(62.07, "今彩五三九牽紅線牽這麼兇"),
                new LyricLine(65.08, "一個牙妹一個魚妹"),
                new LyricLine(67.88, "號碼一簽兩人都中頭獎圈"),
                new LyricLine(70.65, "你說愛情是運氣還是數學題"),
                new LyricLine(76.47, "笑到流淚也只能說一句"),
                new LyricLine(79.43, "最瞎最瞎卻又有點甜蜜"),
                new LyricLine(88.10, "換到小塗這邊"),
                new LyricLine(90.78, "故事居然同一套"),
                new LyricLine(93.61, "今彩五三九播報畫面"),
                new LyricLine(96.95, "他整個人直接跳"),
                new LyricLine(99.47, "魚妹隨手寫的牌"),
                new LyricLine(102.36, "竟然全中好幾排"),
                new LyricLine(105.76, "他說財神爺都點名了"),
                new LyricLine(108.70, "不跟她走進禮堂實在太不應該"),
                new LyricLine(114.62, "鋒兄牽著牙妹"),
                new LyricLine(117.43, "小塗牽著魚妹"),
                new LyricLine(120.33, "喝喜酒的人一桌一桌"),
                new LyricLine(123.42, "還在笑這兩段緣"),
                new LyricLine(126.09, "最瞎結婚理由"),
                new LyricLine(129.10, "結果都開成頭獎"),
                new LyricLine(131.72, "如果幸福也能這樣瞎忙"),
                new LyricLine(135.01, "那我明天也去買一張"),
            },
            new Dictionary<string, string>
            {
                ["鋒兄"] = "鋒兄",
                ["小塗"] = "小塗",
                ["牙妹"] = "牙妹",
                ["魚妹"] = "魚妹",
            },
            new[] { "結婚", "今彩五三九", "命中注定" },
            new Dictionary<string, string>()),
        new(
            "鋒塗力百年夢",
            "鋒兄 × 塗哥｜資訊 × 文化 × 水電科技",
            "song2.mp3",
            new[]
            {
                new LyricLine(10.46, "鋒兄一個念頭"),
                new LyricLine(11.51, "塗哥一起出手"),
                new LyricLine(12.61, "一張桌 一枝筆"),
                new LyricLine(13.99, "畫出未來藍圖走"),
                new LyricLine(15.36, "資訊亮起燈火"),
                new LyricLine(16.73, "文化寫進生活"),
                new LyricLine(17.86, "水電科技串起來"),
                new LyricLine(18.93, "一條路 三個夢同軌"),
                new LyricLine(20.22, "鋒塗力鋒塗力 一起拚下去"),
                new LyricLine(23.67, "百年企業心擔起"),
                new LyricLine(26.25, "今天種的夢 明天變成你福氣"),
                new LyricLine(29.73, "鋒塗力 鋒塗力 就在你身邊一起前進"),
                new LyricLine(39.37, "螢幕後的溫度 字句裡的態度"),
                new LyricLine(41.51, "每一條線 每一支螺絲"),
                new LyricLine(42.81, "都藏著職人的堅固"),
                new LyricLine(44.27, "資訊讓世界接軌"),
                new LyricLine(45.62, "文化替城市發揮"),
                new LyricLine(46.79, "水電科技打底座"),
                new LyricLine(47.78, "安全舒適住進你家裡"),
                new LyricLine(49.30, "鋒塗力鋒塗力 一起拚下去"),
                new LyricLine(53.01, "百年企業心擔起"),
                new LyricLine(55.60, "今天種的夢 明天變成你福氣"),
                new LyricLine(58.64, "鋒塗力 鋒塗力 就在你身邊一起前進"),
                new LyricLine(67.70, "一個鋒 一個塗"),
                new LyricLine(69.19, "名字寫進版圖"),
                new LyricLine(70.20, "從這里 到全國"),
                new LyricLine(71.75, "一步一步走得穩固"),
                new LyricLine(78.01, "鋒塗力鋒塗力 一起拚下去"),
                new LyricLine(81.82, "百年企業心擔起"),
                new LyricLine(84.69, "今天種的夢 明天變成你福氣"),
                new LyricLine(87.71, "鋒塗力 鋒塗力 大家作伙向著未來前進"),
            },
            new Dictionary<string, string>
            {
                ["鋒兄"] = "鋒兄",
                ["小塗"] = "塗哥",
            },
            new[] { "鋒塗力" },
            new Dictionary<string, string>
            {
                ["鋒兄"] = "鋒",
                ["小塗"] = "塗",
            }),
        new(
            "水電進化 Show",
            "水電到樂團的進化論｜台北有大家真好",
            "song3.mp3",
            new[]
            {
                new LyricLine(0.75, "台北有大家真好 嗨起來別逃跑"),
                new LyricLine(17.10, "從水電進化到樂團 這節奏太離譜（wow）"),
                new LyricLine(22.83, "團長唱歌別裝低調 記者都在拍照"),
                new LyricLine(27.99, "吉他至上都說這段人生 根本 S 級歌詞稿"),
                new LyricLine(32.07, "(三十七歲) 那年同學高考三級奪榜首（yeah）"),
                new LyricLine(37.36, "資訊處理一戰成名 程式都寫成傳說"),
                new LyricLine(42.97, "隔著時代的螢幕光 夢想像演算法（run）"),
                new LyricLine(49.74, "(五十二歲) 副市長代理市長上陣忙（yo）"),
                new LyricLine(56.79, "團員敢唱有團長真好"),
                new LyricLine(62.04, "備取瞬間正取秒秒到"),
                new LyricLine(65.26, "不唱就取消資格(笑)"),
                new LyricLine(67.65, "進化不靠運氣靠信號"),
                new LyricLine(75.27, "台北有大家真好 嗨起來別逃跑"),
                new LyricLine(80.63, "從水電進化到樂團 命運像 debug 一樣爆"),
                new LyricLine(88.83, "團長嗓門開到爆表 全場跟著大合唱"),
                new LyricLine(91.78, "代理只是過場 市民心中早就想"),
                new LyricLine(94.14, "(二零四零) 那年的夜 霓虹閃爍到兩廳院"),
                new LyricLine(97.17, "螺絲起子像ACG的opening"),
                new LyricLine(99.58, "別說不可能 大家就是 evolution"),
                new LyricLine(102.56, "(AI) 輔助水管操作 資料開放新世代"),
                new LyricLine(104.61, "陰陽同框 水電與理想 交錯的舞台線上"),
                new LyricLine(107.53, "一首歌唱到粉絲都跳起來 團長還要再唱"),
                new LyricLine(112.61, "(最後副歌) 台北有大家真好 嗨起來直到早朝"),
                new LyricLine(121.76, "(最後副歌) 台北有大家真好 嗨起來直到早朝"),
                new LyricLine(133.46, "水電到樂團的進化論 全城都在尖叫"),
                new LyricLine(139.32, "吉他至上也點頭 這進化合乎理想"),
                new LyricLine(149.60, "有理有理進化論"),
                new LyricLine(156.77, "不 這是水電進化 Show"),
            },
            new Dictionary<string, string>(),
            new[] { "台北有大家真好" },
            new Dictionary<string, string>(),
            new Dictionary<string, IReadOnlyList<string>>
            {
                ["鋒兄"] = new[] { "台北", "吉他", "榜首", "市長", "二零四零" },
                ["小塗"] = new[] { "水電", "團長", "吉他" },
                ["牙妹"] = new[] { "團員", "市民" },
                ["魚妹"] = new[] { "團員", "市民" },
            }),
        new(
            "喵布布本喵掉的毛",
            "本喵親自掉的毛｜尊貴到你不敢吸一口",
            "song4.mp3",
            new[]
            {
                new LyricLine(6.08, "(喵) 人類聽好"),
                new LyricLine(7.68, "低頭跪好"),
                new LyricLine(9.48, "眼睛看好"),
                new LyricLine(11.30, "本喵出場"),
                new LyricLine(13.59, "這不是普通的毛"),
                new LyricLine(15.63, "這是本喵親自掉"),
                new LyricLine(17.34, "一邊躺平打個哈欠"),
                new LyricLine(18.62, "一邊順手送你一撮光耀"),
                new LyricLine(20.72, "翻個身 就灑一地"),
                new LyricLine(22.46, "走兩步 又多幾縷"),
                new LyricLine(24.11, "什麼都沒做都這麼尊貴"),
                new LyricLine(25.70, "你還在那邊算來算去"),
                new LyricLine(27.50, "喵布布本喵掉的毛 (嘿)"),
                new LyricLine(31.02, "尊貴到你不敢吸一口 (不敢吸一口)"),
                new LyricLine(34.42, "每天躺著懶腰就長成寶"),
                new LyricLine(37.86, "想不想要 你自己說"),
                new LyricLine(41.84, "喵布布本喵掉的毛 (喵)"),
                new LyricLine(45.78, "一根一根都帶傲嬌氣味飄"),
                new LyricLine(48.75, "錢放下 人可以走"),
                new LyricLine(51.86, "能不能買到看我心情好不好"),
                new LyricLine(59.58, "貼心標籤 本喵原廠"),
                new LyricLine(61.37, "無人敢仿 假貨滾遠一丈"),
                new LyricLine(63.19, "每一根都含「懶得理你」"),
                new LyricLine(64.94, "過敏？那是你信仰不夠虔誠一點點而已"),
                new LyricLine(68.20, "你在那喊價 888"),
                new LyricLine(70.50, "吵到本喵耳朵都要折"),
                new LyricLine(72.60, "本喵一甩尾巴說 88"),
                new LyricLine(74.34, "給你機會示好 不算太苛"),
                new LyricLine(77.46, "喵布布本喵掉的毛 (喵喵)"),
                new LyricLine(81.33, "尊貴到你不敢吸一口 (深呼吸都抖)"),
                new LyricLine(84.73, "每天躺著懶腰就長成寶"),
                new LyricLine(88.55, "想不想要 你自己說"),
                new LyricLine(92.20, "喵布布本喵掉的毛 (嘿)"),
                new LyricLine(96.00, "一根一根都帶傲嬌氣味飄"),
                new LyricLine(99.20, "錢放下 人可以走"),
                new LyricLine(102.45, "能不能買到看我心情好不好"),
                new LyricLine(107.48, "今天想掉 就掉一床"),
                new LyricLine(111.00, "明天不爽 全部收回去珍藏"),
                new LyricLine(113.84, "後天開心 可能當著你面吞回肚裡"),
                new LyricLine(117.48, "你只剩滑手機看本喵的相片而已 (喵)"),
                new LyricLine(122.72, "喵布布本喵掉的毛"),
                new LyricLine(125.81, "你買到是本喵賞臉的號召"),
                new LyricLine(128.97, "這不是交易 是你向上朝聖一秒"),
                new LyricLine(133.25, "頭低一點 別吵"),
                new LyricLine(137.00, "喵布布本喵掉的毛 (喵~)"),
                new LyricLine(140.80, "最後通牒就說到這麼高傲"),
                new LyricLine(143.76, "錢放下 人可以走"),
                new LyricLine(148.06, "排隊朝拜本喵就好 (喵喵)"),
            },
            new Dictionary<string, string>
            {
                ["喵布布"] = "喵布布",
            },
            Array.Empty<string>(),
            new Dictionary<string, string>(),
            new Dictionary<string, IReadOnlyList<string>>
            {
                ["喵布布"] = new[] { "喵", "喵布布", "本喵" },
            }),
        new(
            "鋒兄的傳奇人生",
            "從頭獎到榜首｜從榜首到總統",
            "song5.mp3",
            new[]
            {
                new LyricLine(11.28, "鋒兄的傳奇人生"),
                new LyricLine(11.28, "從頭獎到榜首"),
                new LyricLine(17.28, "從榜首到總統"),
                new LyricLine(19.85, "三十七歲"),
                new LyricLine(23.25, "統一發票特別獎得主"),
                new LyricLine(29.08, "威力彩頭獎得主"),
                new LyricLine(34.53, "大樂透頭獎得主"),
                new LyricLine(40.26, "高考三級資訊處理榜首"),
                new LyricLine(45.26, "放棄報到"),
                new LyricLine(49.79, "鋒兄塗哥公關資訊"),
                new LyricLine(53.77, "創業"),
                new LyricLine(55.76, "五十一歲"),
                new LyricLine(61.47, "台北市資訊局長"),
                new LyricLine(66.37, "五十二歲"),
                new LyricLine(72.18, "台北市副秘書長"),
                new LyricLine(78.41, "五十四歲"),
                new LyricLine(83.89, "台北市長候選人"),
                new LyricLine(88.23, "百億市長"),
                new LyricLine(92.12, "鋒兄發大財"),
                new LyricLine(95.14, "幸運台北"),
                new LyricLine(98.07, "六十三歲"),
                new LyricLine(99.75, "總統候選人"),
                new LyricLine(103.61, "一兆總統"),
                new LyricLine(108.98, "鋒兄發大財"),
                new LyricLine(111.41, "幸運台灣"),
                new LyricLine(115.67, "鋒兄的傳奇人生"),
                new LyricLine(121.19, "從頭獎到榜首"),
                new LyricLine(127.01, "從榜首到總統"),
            },
            new Dictionary<string, string>
            {
                ["鋒兄"] = "鋒兄",
                ["小塗"] = "塗哥",
            },
            new[] { "公關資訊", "創業", "幸運台北", "幸運台灣" },
            new Dictionary<string, string>(),
            new Dictionary<string, IReadOnlyList<string>>
            {
                ["鋒兄"] = new[] { "頭獎", "榜首", "局長", "副秘書長", "市長", "總統" },
                ["牙妹"] = new[] { "特別獎" },
            }),
        new(
            "塗哥水電王子爆紅",
            "塗神水電王子｜現象級水電工",
            "song6.mp3",
            new[]
            {
                new LyricLine(11.43, "西元兩零零四年六月十五日"),
                new LyricLine(16.02, "這一天是國中畢業生可以在畢業紀念冊留下紀念簽名的一天"),
                new LyricLine(23.23, "同時也是我們故事主角塗神 塗三傑 江湖人稱塗哥一切的開始"),
                new LyricLine(31.81, "塗哥人在台中小吃店 同行指著電視畫面說台北爆發學運太陽花學運 塗哥說我不懂政治 等一下我們去買太陽餅"),
                new LyricLine(42.97, "我聽鋒兄說彰化盛產向日葵 下個月我們去彰化農場踏青 同行職業病發作對農場施工頭頭是道"),
                new LyricLine(56.15, "鋒兄歷史小學堂"),
                new LyricLine(75.67, "林學徒說AI機器人有可能取代水電工 我好焦慮喔 塗哥說可是我聽鋒兄說那是未來不是現在 先作好手邊的工作"),
                new LyricLine(86.00, "塗哥說我有個同學在台北當副市長 同行回你是說鋒兄嗎 鋒兄 怎麼可能 鋒兄現在是青木瓜手搖飲區域經理 副市長是黃馨鋒"),
                new LyricLine(95.94, "同行說我還以為是鋒兄 一樣名字有個鋒字"),
                new LyricLine(101.98, "對了你那同學不出來選台北市長嗎 塗哥說我同學寫了一本有關於水電工的書 他說銷售量超過兩百五十萬冊 才有出來選的本錢"),
                new LyricLine(112.38, "有人在台北動物園快閃唱動物園不得了了 蠟筆小新 塗哥說我不懂日語 等一下我們去KTV唱快樂天堂"),
                new LyricLine(122.15, "塗董 最近的電視劇很火你有在看嗎 水電情 聽說原型人物是塗偉傑 塗偉傑  我叫塗三傑 姓名只差一個字 說不定是我遠房親戚 真的假的 你們塗家壟斷水電這一行業太誇張了吧"),
                new LyricLine(139.06, "塗董 你知道塗偉傑紅到被寫進高職國文課本這件事嗎 哇操 塗偉傑肯定是我遠房親戚 傻眼貓咪 我看鋒兄家的貓都會傻眼"),
                new LyricLine(153.46, "現象級水電工塗哥人物專訪 塗神衍生作品王子 高職國文課本 水電"),
                new LyricLine(163.03, "電視劇 愛上水電工 主題曲鋒兄作詞 小說名場景 青木瓜四木飲冠名播出 鋒兄和塗哥喝青木瓜四木飲一年份喝到吐。"),
                new LyricLine(175.47, "電影 水電工大老闆 學術引用 社會學系碩士論文引用 塗神水電王子 二十一世紀前期文學作品所呈現的台灣社會"),
                new LyricLine(186.95, "國文學系博士論文引用 塗神水電王子 台灣政治人物代表作家及其作品研究"),
                new LyricLine(197.50, "塗哥水電王子爆紅 鋒兄賺三百三十三億 塗哥賺三億"),
            },
            new Dictionary<string, string>
            {
                ["鋒兄"] = "鋒兄",
                ["小塗"] = "塗哥",
            },
            new[] { "西元兩零零四年六月十五日", "國中畢業生" },
            new Dictionary<string, string>
            {
                ["小塗"] = "塗",
            },
            new Dictionary<string, IReadOnlyList<string>>
            {
                ["鋒兄"] = new[] { "政治" },
                ["牙妹"] = new[] { "水電情", "愛上水電工" },
                ["喵布布"] = new[] { "貓" },
            }),
        new(
            "鋒兄進化 Show！🔥",
            "榜首到市長的進化論｜台北有鋒兄真好",
            "song7.mp3",
            new[]
            {
                new LyricLine(0.00, "台北有鋒兄真好"),
                new LyricLine(2.50, "嗨起來別逃跑"),
                new LyricLine(5.21, "從榜首進化到市長 這節奏太離譜（wow）"),
                new LyricLine(11.27, "塗哥唱歌別裝低調"),
                new LyricLine(14.00, "記者都在拍照"),
                new LyricLine(16.00, "實力至上都說這段人生 根本 S 級動畫稿（yeah）"),
                new LyricLine(21.30, "(三十七歲) 那年我高考三級奪榜首"),
                new LyricLine(23.33, "資訊處理一戰成名 程式都寫成傳說"),
                new LyricLine(26.40, "隔著時代的螢幕光 夢想像演算法"),
                new LyricLine(28.98, "(五十二歲) 副市長代理市長上陣忙（yo）"),
                new LyricLine(32.21, "塗哥敢唱有鋒兄真好"),
                new LyricLine(33.66, "備取瞬間正取秒秒到"),
                new LyricLine(35.18, "不唱就取消資格(笑)"),
                new LyricLine(36.49, "進化不靠運氣靠信號"),
                new LyricLine(38.26, "台北有鋒兄真好"),
                new LyricLine(40.41, "嗨起來別逃跑"),
                new LyricLine(41.99, "從榜首進化到市長"),
                new LyricLine(44.79, "命運像 debug 一樣爆"),
                new LyricLine(46.91, "塗哥嗓門開到爆表"),
                new LyricLine(48.58, "全場跟著大合唱"),
                new LyricLine(49.86, "代理只是過場"),
                new LyricLine(50.99, "市民心中早就想"),
                new LyricLine(56.99, "(二零四零) 那年的夜 霓虹閃爍到市政府"),
                new LyricLine(59.55, "競選標語像ACG的opening"),
                new LyricLine(61.99, "別說不可能 鋒兄就是 evolution"),
                new LyricLine(64.27, "(AI) 輔助政務操作 資料開放新世代"),
                new LyricLine(67.00, "陰陽同框 政治與理想 交錯的舞台線上"),
                new LyricLine(69.82, "一首歌唱到選票都跳起來"),
                new LyricLine(71.77, "塗哥還要再唱"),
                new LyricLine(73.00, "(最後副歌) 台北有鋒兄真好"),
                new LyricLine(75.00, "嗨起來直到早朝"),
                new LyricLine(77.52, "榜首到市長的進化論"),
                new LyricLine(80.00, "全城都在尖叫"),
                new LyricLine(82.22, "實力至上也點頭"),
                new LyricLine(83.97, "這進化合乎理想"),
                new LyricLine(85.56, "有理有理進化論"),
                new LyricLine(87.12, "不 這是鋒兄進化 Show"),
                new LyricLine(89.44, "不 這是鋒兄進化 Show"),
                new LyricLine(92.24, "不 這是鋒兄進化 Show"),
            },
            new Dictionary<string, string>
            {
                ["鋒兄"] = "鋒兄",
                ["小塗"] = "塗哥",
            },
            new[] { "鋒兄進化 Show", "台北有鋒兄真好" },
            new Dictionary<string, string>(),
            new Dictionary<string, IReadOnlyList<string>>
            {
                ["鋒兄"] = new[] { "榜首", "市長" },
            }),
        new(
            "我與國中畢業紀念冊的對話",
            "我是國中畢業紀念冊 誰在呼喚我｜鋒兄回答",
            "song8.mp3",
            new[]
            {
                new LyricLine(10.14, "今年是2021年"),
                new LyricLine(13.41, "國中的時候班上有33名學生"),
                new LyricLine(17.31, "剛好我今年生日33歲"),
                new LyricLine(23.50, "我來看看哪幾個班有33名學生"),
                new LyricLine(27.31, "2班不確定 應該沒有33名"),
                new LyricLine(31.00, "5班 12班 18班 23班"),
                new LyricLine(35.02, "這四個班有33名"),
                new LyricLine(39.73, "我想到數學老師有教排列組合"),
                new LyricLine(43.83, "4個數字取2個數字有6種組合"),
                new LyricLine(50.05, "5 12 一組 5 18 一組 5 23 一組"),
                new LyricLine(55.52, "12 18 一組 12 23 一組 18 23 一組"),
                new LyricLine(61.09, "好像沒有意義"),
                new LyricLine(64.74, "我是國中畢業紀念冊 誰在呼喚我"),
                new LyricLine(68.64, "鋒兄回答我是不是幻聽了"),
                new LyricLine(71.20, "國中畢業紀念冊 呼喚 鋒兄"),
                new LyricLine(74.79, "我給你意義 做得到就有意義"),
                new LyricLine(77.73, "做不到就沒意義 意義 怎麼可能有意義"),
                new LyricLine(82.67, "5 12 一組 你有本事考榜首就有意義"),
                new LyricLine(86.59, "我才沒本事考榜首呢"),
                new LyricLine(89.15, "那50分呢 我試試看 2022年最高46分 你太爛了吧"),
                new LyricLine(95.76, "我才不想考試呢 2025年50分 說好的呢 我不考了啦"),
                new LyricLine(101.34, "你37歲一過就可以不再需要考試了"),
                new LyricLine(106.40, "那 真是太好了 反正我本來就不想考試 我真的考到榜首了耶"),
                new LyricLine(114.95, "如果5是五職等 那12就是十二職等"),
                new LyricLine(119.14, "5 12是五十二歲嗎 是也不是 什麼意思"),
                new LyricLine(123.59, "同理你52歲還沒十二職等 這組就結束了"),
                new LyricLine(128.63, "重點是十二職等是副秘書長 而且不是五十二歲"),
                new LyricLine(134.14, "你看是不是還有其他組"),
                new LyricLine(136.97, "對耶 還有其他組 5 18 一組 這組沒意義 跳過"),
                new LyricLine(145.07, "5 23 一組 5班23號 國中補習班同學 這有什麼特別的"),
                new LyricLine(151.64, "你覺得呢 她是公務人員嗎 不是正式的 所以是約聘"),
                new LyricLine(156.67, "你早晚會知道的 所以我就不說了"),
                new LyricLine(159.95, "12 18 一組 有個紫微聖人出來選台北市長耶 好有趣喔"),
                new LyricLine(166.61, "2022年是第8屆市長 第14屆議會"),
                new LyricLine(171.11, "同時往後4屆不就對上了"),
                new LyricLine(173.80, "其他縣市我看看"),
                new LyricLine(175.84, "金門也第8屆可是議會也是第8屆"),
                new LyricLine(179.79, "連江也是第8屆可是議會也是第8屆"),
                new LyricLine(183.65, "沒有了 台北市長 你在開玩笑吧"),
                new LyricLine(187.20, "要當也是當黃大洲之前的市長 有總統挺"),
                new LyricLine(192.19, "12 23 一組 這組沒意義 跳過"),
                new LyricLine(200.16, "18 23 一組 2024年是第16任總統副總統 第11屆立法院"),
                new LyricLine(209.51, "同時往後7屆不就對上了 總統 看起來很正常"),
                new LyricLine(214.42, "台北市長接總統 幹嘛當總統"),
                new LyricLine(218.52, "跟歷史有關係嗎 跟歷史無關的話 沒有非當不可吧"),
                new LyricLine(225.69, "以上是排列組合的對話"),
            },
            new Dictionary<string, string>(),
            new[] { "學生", "國中畢業紀念冊" },
            new Dictionary<string, string>(),
            new Dictionary<string, IReadOnlyList<string>>
            {
                ["鋒兄"] = new[] { "鋒兄", "我" },
                ["牙妹"] = new[] { "5班23號", "國中補習班同學", "她" },
            },
            new Dictionary<string, IReadOnlyList<string>>
            {
                ["鋒兄"] = new[] { "我是國中畢業紀念冊 誰在呼喚我", "我給你意義" },
            }),
        new(
            "統一發票頭獎得主鋒兄威力彩頭獎得主塗哥",
            "招財喵布布送來祝福滿滿｜發票頭獎×威力彩頭獎",
            "song9.mp3",
            new[]
            {
                new LyricLine(11.20, "招財喵布布送來祝福滿滿"),
                new LyricLine(14.00, "祝鋒兄三十七歲快樂相伴"),
                new LyricLine(17.00, "生日禮物是發票頭獎兌現"),
                new LyricLine(20.00, "二十萬元整讓你笑開顏"),
                new LyricLine(22.87, "塗哥明年生日願望要實現"),
                new LyricLine(27.50, "威力彩頭獎就在眼前"),
                new LyricLine(34.95, "鋒兄買單六人份四千八"),
                new LyricLine(40.00, "塗哥選號中獎"),
                new LyricLine(42.06, "分紅兩千零二十五萬發"),
                new LyricLine(45.50, "全家共享這份幸運呀"),
                new LyricLine(51.00, "招財喵布布把幸福播撒"),
                new LyricLine(65.50, "塗哥爸媽"),
                new LyricLine(66.59, "鋒兄爸媽"),
                new LyricLine(67.68, "都到場"),
                new LyricLine(68.50, "招財喵布布見證這歡暢"),
                new LyricLine(71.00, "幸運之神眷顧這個家"),
                new LyricLine(73.50, "財富和快樂永遠不散場"),
                new LyricLine(76.50, "塗哥明年生日願望要實現"),
                new LyricLine(81.50, "威力彩頭獎就在眼前"),
                new LyricLine(88.50, "鋒兄買單六人份四千八"),
                new LyricLine(94.00, "塗哥選號中獎"),
                new LyricLine(96.06, "分紅兩千零二十五萬發"),
                new LyricLine(99.50, "全家共享這份幸運呀"),
                new LyricLine(104.94, "招財喵布布把幸福播撒"),
            },
            new Dictionary<string, string>
            {
                ["鋒兄"] = "鋒兄",
                ["小塗"] = "塗哥",
                ["喵布布"] = "喵布布",
            },
            new[] { "威力彩頭獎", "全家" },
            new Dictionary<string, string>()),
    };
}
