package com.qwentest.lyricsplayer

data class LyricLine(val timeMs: Int, val text: String)

data class Song(
    val title: String,
    val subtitle: String,
    val audioFile: String,
    val lines: List<LyricLine>,
    // avatar view id -> 歌詞中對應的名字
    val characterNames: Map<String, String>,
    // 出現任一關鍵字 -> 四位角色同時亮燈
    val allWords: List<String> = emptyList(),
    // avatar view id -> 單字觸發（如「鋒」字亮鋒兄）
    val charTriggers: Map<String, String> = emptyMap(),
)

object LyricsData {
    val songs: List<Song> = listOf(
        Song(
            title = "最瞎結婚理由",
            subtitle = "鋒兄 × 小塗 × 牙妹 × 魚妹｜今彩五三九牽紅線",
            audioFile = "song1.mp3",
            lines = listOf(
                LyricLine(20600, "鋒兄啊你說真的還假的"),
                LyricLine(26380, "小塗聽了都快笑翻了"),
                LyricLine(32300, "鋒兄說要結婚"),
                LyricLine(35100, "理由只有一個"),
                LyricLine(38230, "今彩五三九開獎那天"),
                LyricLine(41390, "頭獎號碼是牙妹給的"),
                LyricLine(43810, "看著獎金直直落"),
                LyricLine(47130, "心也跟著被收編"),
                LyricLine(49860, "他說這是命中注定"),
                LyricLine(52760, "不娶怎麼對得起這一連串的玄"),
                LyricLine(58760, "史上最瞎結婚理由"),
                LyricLine(62070, "今彩五三九牽紅線牽這麼兇"),
                LyricLine(65080, "一個牙妹一個魚妹"),
                LyricLine(67880, "號碼一簽兩人都中頭獎圈"),
                LyricLine(70650, "你說愛情是運氣還是數學題"),
                LyricLine(76470, "笑到流淚也只能說一句"),
                LyricLine(79430, "最瞎最瞎卻又有點甜蜜"),
                LyricLine(88100, "換到小塗這邊"),
                LyricLine(90780, "故事居然同一套"),
                LyricLine(93610, "今彩五三九播報畫面"),
                LyricLine(96950, "他整個人直接跳"),
                LyricLine(99470, "魚妹隨手寫的牌"),
                LyricLine(102360, "竟然全中好幾排"),
                LyricLine(105760, "他說財神爺都點名了"),
                LyricLine(108700, "不跟她走進禮堂實在太不應該"),
                LyricLine(114620, "鋒兄牽著牙妹"),
                LyricLine(117430, "小塗牽著魚妹"),
                LyricLine(120330, "喝喜酒的人一桌一桌"),
                LyricLine(123420, "還在笑這兩段緣"),
                LyricLine(126090, "最瞎結婚理由"),
                LyricLine(129100, "結果都開成頭獎"),
                LyricLine(131720, "如果幸福也能這樣瞎忙"),
                LyricLine(135010, "那我明天也去買一張"),
            ),
            characterNames = mapOf(
                "avatar_feng" to "鋒兄",
                "avatar_tu" to "小塗",
                "avatar_ya" to "牙妹",
                "avatar_yu" to "魚妹",
            ),
            allWords = listOf("結婚", "今彩五三九", "命中注定"),
        ),
        Song(
            title = "鋒塗力百年夢",
            subtitle = "鋒兄 × 塗哥｜資訊 × 文化 × 水電科技",
            audioFile = "song2.mp3",
            lines = listOf(
                LyricLine(10460, "鋒兄一個念頭"),
                LyricLine(11510, "塗哥一起出手"),
                LyricLine(12610, "一張桌 一枝筆"),
                LyricLine(13990, "畫出未來藍圖走"),
                LyricLine(15360, "資訊亮起燈火"),
                LyricLine(16730, "文化寫進生活"),
                LyricLine(17860, "水電科技串起來"),
                LyricLine(18930, "一條路 三個夢同軌"),
                LyricLine(20220, "鋒塗力鋒塗力 一起拚下去"),
                LyricLine(23670, "百年企業心擔起"),
                LyricLine(26250, "今天種的夢 明天變成你福氣"),
                LyricLine(29730, "鋒塗力 鋒塗力 就在你身邊一起前進"),
                LyricLine(39370, "螢幕後的溫度 字句裡的態度"),
                LyricLine(41510, "每一條線 每一支螺絲"),
                LyricLine(42810, "都藏著職人的堅固"),
                LyricLine(44270, "資訊讓世界接軌"),
                LyricLine(45620, "文化替城市發揮"),
                LyricLine(46790, "水電科技打底座"),
                LyricLine(47780, "安全舒適住進你家裡"),
                LyricLine(49300, "鋒塗力鋒塗力 一起拚下去"),
                LyricLine(53010, "百年企業心擔起"),
                LyricLine(55600, "今天種的夢 明天變成你福氣"),
                LyricLine(58640, "鋒塗力 鋒塗力 就在你身邊一起前進"),
                LyricLine(67700, "一個鋒 一個塗"),
                LyricLine(69190, "名字寫進版圖"),
                LyricLine(70200, "從這里 到全國"),
                LyricLine(71750, "一步一步走得穩固"),
                LyricLine(78010, "鋒塗力鋒塗力 一起拚下去"),
                LyricLine(81820, "百年企業心擔起"),
                LyricLine(84690, "今天種的夢 明天變成你福氣"),
                LyricLine(87710, "鋒塗力 鋒塗力 大家作伙向著未來前進"),
            ),
            characterNames = mapOf(
                "avatar_feng" to "鋒兄",
                "avatar_tu" to "塗哥",
            ),
            allWords = listOf("鋒塗力"),
            charTriggers = mapOf(
                "avatar_feng" to "鋒",
                "avatar_tu" to "塗",
            ),
        ),
    )
}
