package com.qwentest.lyricsplayer

data class LyricLine(val timeMs: Int, val text: String)

data class Song(
    val title: String,
    val subtitle: String,
    val audioFile: String,
    val lines: List<LyricLine>,
    // avatar view id -> 歌詞中對應的名字
    val characterNames: Map<String, String>,
    // 出現任一關鍵字 -> 四位角色同時亮燈
    val allWords: List<String> = emptyList(),
    // avatar view id -> 單字觸發（如「鋒」字亮鋒兄）
    val charTriggers: Map<String, String> = emptyMap(),
    // avatar view id -> 多關鍵字，任一命中即亮燈
    val characterKeywords: Map<String, List<String>> = emptyMap(),
    // avatar view id -> 排除片語，歌詞含任一排除片語時該角色不亮燈
    val characterExclude: Map<String, List<String>> = emptyMap(),
)

object LyricsData {
    val songs: List<Song> = listOf(
        Song(
            title = "最瞎結婚理由",
            subtitle = "鋒兄 × 小塗 × 牙妹 × 魚妹｜今彩五三九牽紅線",
            audioFile = "song1.mp3",
            lines = listOf(
                LyricLine(20600, "鋒兄啊你說真的還假的"),
                LyricLine(26380, "小塗聽了都快笑翻了"),
                LyricLine(32300, "鋒兄說要結婚"),
                LyricLine(35100, "理由只有一個"),
                LyricLine(38230, "今彩五三九開獎那天"),
                LyricLine(41390, "頭獎號碼是牙妹給的"),
                LyricLine(43810, "看著獎金直直落"),
                LyricLine(47130, "心也跟著被收編"),
                LyricLine(49860, "他說這是命中注定"),
                LyricLine(52760, "不娶怎麼對得起這一連串的玄"),
                LyricLine(58760, "史上最瞎結婚理由"),
                LyricLine(62070, "今彩五三九牽紅線牽這麼兇"),
                LyricLine(65080, "一個牙妹一個魚妹"),
                LyricLine(67880, "號碼一簽兩人都中頭獎圈"),
                LyricLine(70650, "你說愛情是運氣還是數學題"),
                LyricLine(76470, "笑到流淚也只能說一句"),
                LyricLine(79430, "最瞎最瞎卻又有點甜蜜"),
                LyricLine(88100, "換到小塗這邊"),
                LyricLine(90780, "故事居然同一套"),
                LyricLine(93610, "今彩五三九播報畫面"),
                LyricLine(96950, "他整個人直接跳"),
                LyricLine(99470, "魚妹隨手寫的牌"),
                LyricLine(102360, "竟然全中好幾排"),
                LyricLine(105760, "他說財神爺都點名了"),
                LyricLine(108700, "不跟她走進禮堂實在太不應該"),
                LyricLine(114620, "鋒兄牽著牙妹"),
                LyricLine(117430, "小塗牽著魚妹"),
                LyricLine(120330, "喝喜酒的人一桌一桌"),
                LyricLine(123420, "還在笑這兩段緣"),
                LyricLine(126090, "最瞎結婚理由"),
                LyricLine(129100, "結果都開成頭獎"),
                LyricLine(131720, "如果幸福也能這樣瞎忙"),
                LyricLine(135010, "那我明天也去買一張"),
            ),
            characterNames = mapOf(
                "avatar_feng" to "鋒兄",
                "avatar_tu" to "小塗",
                "avatar_ya" to "牙妹",
                "avatar_yu" to "魚妹",
            ),
            allWords = listOf("結婚", "今彩五三九", "命中注定"),
        ),
        Song(
            title = "鋒塗力百年夢",
            subtitle = "鋒兄 × 塗哥｜資訊 × 文化 × 水電科技",
            audioFile = "song2.mp3",
            lines = listOf(
                LyricLine(10460, "鋒兄一個念頭"),
                LyricLine(11510, "塗哥一起出手"),
                LyricLine(12610, "一張桌 一枝筆"),
                LyricLine(13990, "畫出未來藍圖走"),
                LyricLine(15360, "資訊亮起燈火"),
                LyricLine(16730, "文化寫進生活"),
                LyricLine(17860, "水電科技串起來"),
                LyricLine(18930, "一條路 三個夢同軌"),
                LyricLine(20220, "鋒塗力鋒塗力 一起拚下去"),
                LyricLine(23670, "百年企業心擔起"),
                LyricLine(26250, "今天種的夢 明天變成你福氣"),
                LyricLine(29730, "鋒塗力 鋒塗力 就在你身邊一起前進"),
                LyricLine(39370, "螢幕後的溫度 字句裡的態度"),
                LyricLine(41510, "每一條線 每一支螺絲"),
                LyricLine(42810, "都藏著職人的堅固"),
                LyricLine(44270, "資訊讓世界接軌"),
                LyricLine(45620, "文化替城市發揮"),
                LyricLine(46790, "水電科技打底座"),
                LyricLine(47780, "安全舒適住進你家裡"),
                LyricLine(49300, "鋒塗力鋒塗力 一起拚下去"),
                LyricLine(53010, "百年企業心擔起"),
                LyricLine(55600, "今天種的夢 明天變成你福氣"),
                LyricLine(58640, "鋒塗力 鋒塗力 就在你身邊一起前進"),
                LyricLine(67700, "一個鋒 一個塗"),
                LyricLine(69190, "名字寫進版圖"),
                LyricLine(70200, "從這里 到全國"),
                LyricLine(71750, "一步一步走得穩固"),
                LyricLine(78010, "鋒塗力鋒塗力 一起拚下去"),
                LyricLine(81820, "百年企業心擔起"),
                LyricLine(84690, "今天種的夢 明天變成你福氣"),
                LyricLine(87710, "鋒塗力 鋒塗力 大家作伙向著未來前進"),
            ),
            characterNames = mapOf(
                "avatar_feng" to "鋒兄",
                "avatar_tu" to "塗哥",
            ),
            allWords = listOf("鋒塗力"),
            charTriggers = mapOf(
                "avatar_feng" to "鋒",
                "avatar_tu" to "塗",
            ),
        ),
        Song(
            title = "水電進化 Show",
            subtitle = "水電到樂團的進化論｜台北有大家真好",
            audioFile = "song3.mp3",
            lines = listOf(
                LyricLine(750, "台北有大家真好 嗨起來別逃跑"),
                LyricLine(17100, "從水電進化到樂團 這節奏太離譜（wow）"),
                LyricLine(22830, "團長唱歌別裝低調 記者都在拍照"),
                LyricLine(27990, "吉他至上都說這段人生 根本 S 級歌詞稿"),
                LyricLine(32070, "(三十七歲) 那年同學高考三級奪榜首（yeah）"),
                LyricLine(37360, "資訊處理一戰成名 程式都寫成傳說"),
                LyricLine(42970, "隔著時代的螢幕光 夢想像演算法（run）"),
                LyricLine(49740, "(五十二歲) 副市長代理市長上陣忙（yo）"),
                LyricLine(56790, "團員敢唱有團長真好"),
                LyricLine(62040, "備取瞬間正取秒秒到"),
                LyricLine(65260, "不唱就取消資格(笑)"),
                LyricLine(67650, "進化不靠運氣靠信號"),
                LyricLine(75270, "台北有大家真好 嗨起來別逃跑"),
                LyricLine(80630, "從水電進化到樂團 命運像 debug 一樣爆"),
                LyricLine(88830, "團長嗓門開到爆表 全場跟著大合唱"),
                LyricLine(91780, "代理只是過場 市民心中早就想"),
                LyricLine(94140, "(二零四零) 那年的夜 霓虹閃爍到兩廳院"),
                LyricLine(97170, "螺絲起子像ACG的opening"),
                LyricLine(99580, "別說不可能 大家就是 evolution"),
                LyricLine(102560, "(AI) 輔助水管操作 資料開放新世代"),
                LyricLine(104610, "陰陽同框 水電與理想 交錯的舞台線上"),
                LyricLine(107530, "一首歌唱到粉絲都跳起來 團長還要再唱"),
                LyricLine(112610, "(最後副歌) 台北有大家真好 嗨起來直到早朝"),
                LyricLine(121760, "(最後副歌) 台北有大家真好 嗨起來直到早朝"),
                LyricLine(133460, "水電到樂團的進化論 全城都在尖叫"),
                LyricLine(139320, "吉他至上也點頭 這進化合乎理想"),
                LyricLine(149600, "有理有理進化論"),
                LyricLine(156770, "不 這是水電進化 Show"),
            ),
            characterNames = emptyMap(),
            allWords = listOf("台北有大家真好"),
            characterKeywords = mapOf(
                "avatar_feng" to listOf("台北", "吉他", "榜首", "市長", "二零四零"),
                "avatar_tu" to listOf("水電", "團長", "吉他"),
                "avatar_ya" to listOf("團員", "市民"),
                "avatar_yu" to listOf("團員", "市民"),
            ),
        ),
        Song(
            title = "喵布布本喵掉的毛",
            subtitle = "本喵親自掉的毛｜尊貴到你不敢吸一口",
            audioFile = "song4.mp3",
            lines = listOf(
                LyricLine(6080, "(喵) 人類聽好"),
                LyricLine(7680, "低頭跪好"),
                LyricLine(9480, "眼睛看好"),
                LyricLine(11300, "本喵出場"),
                LyricLine(13590, "這不是普通的毛"),
                LyricLine(15630, "這是本喵親自掉"),
                LyricLine(17340, "一邊躺平打個哈欠"),
                LyricLine(18620, "一邊順手送你一撮光耀"),
                LyricLine(20720, "翻個身 就灑一地"),
                LyricLine(22460, "走兩步 又多幾縷"),
                LyricLine(24110, "什麼都沒做都這麼尊貴"),
                LyricLine(25700, "你還在那邊算來算去"),
                LyricLine(27500, "喵布布本喵掉的毛 (嘿)"),
                LyricLine(31020, "尊貴到你不敢吸一口 (不敢吸一口)"),
                LyricLine(34420, "每天躺著懶腰就長成寶"),
                LyricLine(37860, "想不想要 你自己說"),
                LyricLine(41840, "喵布布本喵掉的毛 (喵)"),
                LyricLine(45780, "一根一根都帶傲嬌氣味飄"),
                LyricLine(48750, "錢放下 人可以走"),
                LyricLine(51860, "能不能買到看我心情好不好"),
                LyricLine(59580, "貼心標籤 本喵原廠"),
                LyricLine(61370, "無人敢仿 假貨滾遠一丈"),
                LyricLine(63190, "每一根都含「懶得理你」"),
                LyricLine(64940, "過敏？那是你信仰不夠虔誠一點點而已"),
                LyricLine(68200, "你在那喊價 888"),
                LyricLine(70500, "吵到本喵耳朵都要折"),
                LyricLine(72600, "本喵一甩尾巴說 88"),
                LyricLine(74340, "給你機會示好 不算太苛"),
                LyricLine(77460, "喵布布本喵掉的毛 (喵喵)"),
                LyricLine(81330, "尊貴到你不敢吸一口 (深呼吸都抖)"),
                LyricLine(84730, "每天躺著懶腰就長成寶"),
                LyricLine(88550, "想不想要 你自己說"),
                LyricLine(92200, "喵布布本喵掉的毛 (嘿)"),
                LyricLine(96000, "一根一根都帶傲嬌氣味飄"),
                LyricLine(99200, "錢放下 人可以走"),
                LyricLine(102450, "能不能買到看我心情好不好"),
                LyricLine(107480, "今天想掉 就掉一床"),
                LyricLine(111000, "明天不爽 全部收回去珍藏"),
                LyricLine(113840, "後天開心 可能當著你面吞回肚裡"),
                LyricLine(117480, "你只剩滑手機看本喵的相片而已 (喵)"),
                LyricLine(122720, "喵布布本喵掉的毛"),
                LyricLine(125810, "你買到是本喵賞臉的號召"),
                LyricLine(128970, "這不是交易 是你向上朝聖一秒"),
                LyricLine(133250, "頭低一點 別吵"),
                LyricLine(137000, "喵布布本喵掉的毛 (喵~)"),
                LyricLine(140800, "最後通牒就說到這麼高傲"),
                LyricLine(143760, "錢放下 人可以走"),
                LyricLine(148060, "排隊朝拜本喵就好 (喵喵)"),
            ),
            characterNames = mapOf(
                "avatar_miao" to "喵布布",
            ),
            characterKeywords = mapOf(
                "avatar_miao" to listOf("喵", "喵布布", "本喵"),
            ),
        ),
        Song(
            title = "鋒兄的傳奇人生",
            subtitle = "從頭獎到榜首｜從榜首到總統",
            audioFile = "song5.mp3",
            lines = listOf(
                LyricLine(11280, "鋒兄的傳奇人生"),
                LyricLine(11280, "從頭獎到榜首"),
                LyricLine(17280, "從榜首到總統"),
                LyricLine(19850, "三十七歲"),
                LyricLine(23250, "統一發票特別獎得主"),
                LyricLine(29080, "威力彩頭獎得主"),
                LyricLine(34530, "大樂透頭獎得主"),
                LyricLine(40260, "高考三級資訊處理榜首"),
                LyricLine(45260, "放棄報到"),
                LyricLine(49790, "鋒兄塗哥公關資訊"),
                LyricLine(53770, "創業"),
                LyricLine(55760, "五十一歲"),
                LyricLine(61470, "台北市資訊局長"),
                LyricLine(66370, "五十二歲"),
                LyricLine(72180, "台北市副秘書長"),
                LyricLine(78410, "五十四歲"),
                LyricLine(83890, "台北市長候選人"),
                LyricLine(88230, "百億市長"),
                LyricLine(92120, "鋒兄發大財"),
                LyricLine(95140, "幸運台北"),
                LyricLine(98070, "六十三歲"),
                LyricLine(99750, "總統候選人"),
                LyricLine(103610, "一兆總統"),
                LyricLine(108980, "鋒兄發大財"),
                LyricLine(111410, "幸運台灣"),
                LyricLine(115670, "鋒兄的傳奇人生"),
                LyricLine(121190, "從頭獎到榜首"),
                LyricLine(127010, "從榜首到總統"),
            ),
            characterNames = mapOf(
                "avatar_feng" to "鋒兄",
                "avatar_tu" to "塗哥",
            ),
            allWords = listOf("公關資訊", "創業", "幸運台北", "幸運台灣"),
            characterKeywords = mapOf(
                "avatar_feng" to listOf("頭獎", "榜首", "局長", "副秘書長", "市長", "總統"),
                "avatar_ya" to listOf("特別獎"),
            ),
        ),
        Song(
            title = "塗哥水電王子爆紅",
            subtitle = "塗神水電王子｜現象級水電工",
            audioFile = "song6.mp3",
            lines = listOf(
                LyricLine(11430, "西元兩零零四年六月十五日"),
                LyricLine(16020, "這一天是國中畢業生可以在畢業紀念冊留下紀念簽名的一天"),
                LyricLine(23230, "同時也是我們故事主角塗神 塗三傑 江湖人稱塗哥一切的開始"),
                LyricLine(31810, "塗哥人在台中小吃店 同行指著電視畫面說台北爆發學運太陽花學運 塗哥說我不懂政治 等一下我們去買太陽餅"),
                LyricLine(42970, "我聽鋒兄說彰化盛產向日葵 下個月我們去彰化農場踏青 同行職業病發作對農場施工頭頭是道"),
                LyricLine(56150, "鋒兄歷史小學堂"),
                LyricLine(75670, "林學徒說AI機器人有可能取代水電工 我好焦慮喔 塗哥說可是我聽鋒兄說那是未來不是現在 先作好手邊的工作"),
                LyricLine(86000, "塗哥說我有個同學在台北當副市長 同行回你是說鋒兄嗎 鋒兄 怎麼可能 鋒兄現在是青木瓜手搖飲區域經理 副市長是黃馨鋒"),
                LyricLine(95940, "同行說我還以為是鋒兄 一樣名字有個鋒字"),
                LyricLine(101980, "對了你那同學不出來選台北市長嗎 塗哥說我同學寫了一本有關於水電工的書 他說銷售量超過兩百五十萬冊 才有出來選的本錢"),
                LyricLine(112380, "有人在台北動物園快閃唱動物園不得了了 蠟筆小新 塗哥說我不懂日語 等一下我們去KTV唱快樂天堂"),
                LyricLine(122150, "塗董 最近的電視劇很火你有在看嗎 水電情 聽說原型人物是塗偉傑 塗偉傑  我叫塗三傑 姓名只差一個字 說不定是我遠房親戚 真的假的 你們塗家壟斷水電這一行業太誇張了吧"),
                LyricLine(139060, "塗董 你知道塗偉傑紅到被寫進高職國文課本這件事嗎 哇操 塗偉傑肯定是我遠房親戚 傻眼貓咪 我看鋒兄家的貓都會傻眼"),
                LyricLine(153460, "現象級水電工塗哥人物專訪 塗神衍生作品王子 高職國文課本 水電"),
                LyricLine(163030, "電視劇 愛上水電工 主題曲鋒兄作詞 小說名場景 青木瓜四木飲冠名播出 鋒兄和塗哥喝青木瓜四木飲一年份喝到吐。"),
                LyricLine(175470, "電影 水電工大老闆 學術引用 社會學系碩士論文引用 塗神水電王子 二十一世紀前期文學作品所呈現的台灣社會"),
                LyricLine(186950, "國文學系博士論文引用 塗神水電王子 台灣政治人物代表作家及其作品研究"),
                LyricLine(197500, "塗哥水電王子爆紅 鋒兄賺三百三十三億 塗哥賺三億"),
            ),
            characterNames = mapOf(
                "avatar_feng" to "鋒兄",
                "avatar_tu" to "塗哥",
            ),
            allWords = listOf("西元兩零零四年六月十五日", "國中畢業生"),
            charTriggers = mapOf(
                "avatar_tu" to "塗",
            ),
            characterKeywords = mapOf(
                "avatar_feng" to listOf("政治"),
                "avatar_ya" to listOf("水電情", "愛上水電工"),
                "avatar_miao" to listOf("貓"),
            ),
        ),
        Song(
            title = "鋒兄進化 Show！🔥",
            subtitle = "榜首到市長的進化論｜台北有鋒兄真好",
            audioFile = "song7.mp3",
            lines = listOf(
                LyricLine(0, "台北有鋒兄真好"),
                LyricLine(2500, "嗨起來別逃跑"),
                LyricLine(5210, "從榜首進化到市長 這節奏太離譜（wow）"),
                LyricLine(11270, "塗哥唱歌別裝低調"),
                LyricLine(14000, "記者都在拍照"),
                LyricLine(16000, "實力至上都說這段人生 根本 S 級動畫稿（yeah）"),
                LyricLine(21300, "(三十七歲) 那年我高考三級奪榜首"),
                LyricLine(23330, "資訊處理一戰成名 程式都寫成傳說"),
                LyricLine(26400, "隔著時代的螢幕光 夢想像演算法"),
                LyricLine(28980, "(五十二歲) 副市長代理市長上陣忙（yo）"),
                LyricLine(32210, "塗哥敢唱有鋒兄真好"),
                LyricLine(33660, "備取瞬間正取秒秒到"),
                LyricLine(35180, "不唱就取消資格(笑)"),
                LyricLine(36490, "進化不靠運氣靠信號"),
                LyricLine(38260, "台北有鋒兄真好"),
                LyricLine(40410, "嗨起來別逃跑"),
                LyricLine(41990, "從榜首進化到市長"),
                LyricLine(44790, "命運像 debug 一樣爆"),
                LyricLine(46910, "塗哥嗓門開到爆表"),
                LyricLine(48580, "全場跟著大合唱"),
                LyricLine(49860, "代理只是過場"),
                LyricLine(50990, "市民心中早就想"),
                LyricLine(56990, "(二零四零) 那年的夜 霓虹閃爍到市政府"),
                LyricLine(59550, "競選標語像ACG的opening"),
                LyricLine(61990, "別說不可能 鋒兄就是 evolution"),
                LyricLine(64270, "(AI) 輔助政務操作 資料開放新世代"),
                LyricLine(67000, "陰陽同框 政治與理想 交錯的舞台線上"),
                LyricLine(69820, "一首歌唱到選票都跳起來"),
                LyricLine(71770, "塗哥還要再唱"),
                LyricLine(73000, "(最後副歌) 台北有鋒兄真好"),
                LyricLine(75000, "嗨起來直到早朝"),
                LyricLine(77520, "榜首到市長的進化論"),
                LyricLine(80000, "全城都在尖叫"),
                LyricLine(82220, "實力至上也點頭"),
                LyricLine(83970, "這進化合乎理想"),
                LyricLine(85560, "有理有理進化論"),
                LyricLine(87120, "不 這是鋒兄進化 Show"),
                LyricLine(89440, "不 這是鋒兄進化 Show"),
                LyricLine(92240, "不 這是鋒兄進化 Show"),
            ),
            characterNames = mapOf(
                "avatar_feng" to "鋒兄",
                "avatar_tu" to "塗哥",
            ),
            allWords = listOf("鋒兄進化 Show", "台北有鋒兄真好"),
            characterKeywords = mapOf(
                "avatar_feng" to listOf("榜首", "市長"),
            ),
        ),
        Song(
            title = "我與國中畢業紀念冊的對話",
            subtitle = "我是國中畢業紀念冊 誰在呼喚我｜鋒兄回答",
            audioFile = "song8.mp3",
            lines = listOf(
                LyricLine(10140, "今年是2021年"),
                LyricLine(13410, "國中的時候班上有33名學生"),
                LyricLine(17310, "剛好我今年生日33歲"),
                LyricLine(23500, "我來看看哪幾個班有33名學生"),
                LyricLine(27310, "2班不確定 應該沒有33名"),
                LyricLine(31000, "5班 12班 18班 23班"),
                LyricLine(35020, "這四個班有33名"),
                LyricLine(39730, "我想到數學老師有教排列組合"),
                LyricLine(43830, "4個數字取2個數字有6種組合"),
                LyricLine(50050, "5 12 一組 5 18 一組 5 23 一組"),
                LyricLine(55520, "12 18 一組 12 23 一組 18 23 一組"),
                LyricLine(61090, "好像沒有意義"),
                LyricLine(64740, "我是國中畢業紀念冊 誰在呼喚我"),
                LyricLine(68640, "鋒兄回答我是不是幻聽了"),
                LyricLine(71200, "國中畢業紀念冊 呼喚 鋒兄"),
                LyricLine(74790, "我給你意義 做得到就有意義"),
                LyricLine(77730, "做不到就沒意義 意義 怎麼可能有意義"),
                LyricLine(82670, "5 12 一組 你有本事考榜首就有意義"),
                LyricLine(86590, "我才沒本事考榜首呢"),
                LyricLine(89150, "那50分呢 我試試看 2022年最高46分 你太爛了吧"),
                LyricLine(95760, "我才不想考試呢 2025年50分 說好的呢 我不考了啦"),
                LyricLine(101340, "你37歲一過就可以不再需要考試了"),
                LyricLine(106400, "那 真是太好了 反正我本來就不想考試 我真的考到榜首了耶"),
                LyricLine(114950, "如果5是五職等 那12就是十二職等"),
                LyricLine(119140, "5 12是五十二歲嗎 是也不是 什麼意思"),
                LyricLine(123590, "同理你52歲還沒十二職等 這組就結束了"),
                LyricLine(128630, "重點是十二職等是副秘書長 而且不是五十二歲"),
                LyricLine(134140, "你看是不是還有其他組"),
                LyricLine(136970, "對耶 還有其他組 5 18 一組 這組沒意義 跳過"),
                LyricLine(145070, "5 23 一組 5班23號 國中補習班同學 這有什麼特別的"),
                LyricLine(151640, "你覺得呢 她是公務人員嗎 不是正式的 所以是約聘"),
                LyricLine(156670, "你早晚會知道的 所以我就不說了"),
                LyricLine(159950, "12 18 一組 有個紫微聖人出來選台北市長耶 好有趣喔"),
                LyricLine(166610, "2022年是第8屆市長 第14屆議會"),
                LyricLine(171110, "同時往後4屆不就對上了"),
                LyricLine(173800, "其他縣市我看看"),
                LyricLine(175840, "金門也第8屆可是議會也是第8屆"),
                LyricLine(179790, "連江也是第8屆可是議會也是第8屆"),
                LyricLine(183650, "沒有了 台北市長 你在開玩笑吧"),
                LyricLine(187200, "要當也是當黃大洲之前的市長 有總統挺"),
                LyricLine(192190, "12 23 一組 這組沒意義 跳過"),
                LyricLine(200160, "18 23 一組 2024年是第16任總統副總統 第11屆立法院"),
                LyricLine(209510, "同時往後7屆不就對上了 總統 看起來很正常"),
                LyricLine(214420, "台北市長接總統 幹嘛當總統"),
                LyricLine(218520, "跟歷史有關係嗎 跟歷史無關的話 沒有非當不可吧"),
                LyricLine(225690, "以上是排列組合的對話"),
            ),
            characterNames = emptyMap(),
            allWords = listOf("學生", "國中畢業紀念冊"),
            characterKeywords = mapOf(
                "avatar_feng" to listOf("鋒兄", "我"),
                "avatar_ya" to listOf("5班23號", "國中補習班同學", "她"),
            ),
            characterExclude = mapOf(
                "avatar_feng" to listOf("我是國中畢業紀念冊 誰在呼喚我", "我給你意義"),
            ),
        ),
        Song(
            title = "統一發票頭獎得主鋒兄威力彩頭獎得主塗哥",
            subtitle = "招財喵布布送來祝福滿滿｜發票頭獎×威力彩頭獎",
            audioFile = "song9.mp3",
            lines = listOf(
                LyricLine(11200, "招財喵布布送來祝福滿滿"),
                LyricLine(14000, "祝鋒兄三十七歲快樂相伴"),
                LyricLine(17000, "生日禮物是發票頭獎兌現"),
                LyricLine(20000, "二十萬元整讓你笑開顏"),
                LyricLine(22870, "塗哥明年生日願望要實現"),
                LyricLine(27500, "威力彩頭獎就在眼前"),
                LyricLine(34950, "鋒兄買單六人份四千八"),
                LyricLine(40000, "塗哥選號中獎"),
                LyricLine(42060, "分紅兩千零二十五萬發"),
                LyricLine(45500, "全家共享這份幸運呀"),
                LyricLine(51000, "招財喵布布把幸福播撒"),
                LyricLine(65500, "塗哥爸媽"),
                LyricLine(66590, "鋒兄爸媽"),
                LyricLine(67680, "都到場"),
                LyricLine(68500, "招財喵布布見證這歡暢"),
                LyricLine(71000, "幸運之神眷顧這個家"),
                LyricLine(73500, "財富和快樂永遠不散場"),
                LyricLine(76500, "塗哥明年生日願望要實現"),
                LyricLine(81500, "威力彩頭獎就在眼前"),
                LyricLine(88500, "鋒兄買單六人份四千八"),
                LyricLine(94000, "塗哥選號中獎"),
                LyricLine(96060, "分紅兩千零二十五萬發"),
                LyricLine(99500, "全家共享這份幸運呀"),
                LyricLine(104940, "招財喵布布把幸福播撒"),
            ),
            characterNames = mapOf(
                "avatar_feng" to "鋒兄",
                "avatar_tu" to "塗哥",
                "avatar_miao" to "喵布布",
            ),
            allWords = listOf("威力彩頭獎", "全家"),
        ),
    )
}
